name: CI Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install data-processing-v2 dependencies
        run: npm install
        working-directory: ./data-processing-v2

      - name: Generate V2 data (with 3.0 hypothetical version)
        run: |
          npm run generate -- --include-3.0
          npm run copy-to-frontend
        working-directory: ./data-processing-v2

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run linting
        run: npm run lint
        working-directory: ./frontend

      - name: Run unit tests
        run: npm run test:run
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Install Playwright browsers
        run: npx playwright install chromium
        working-directory: ./frontend

      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: ./frontend
