name: Update Instrumentation List

on:
  # Run daily at 9 AM UTC
  schedule:
    - cron: '0 9 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-instrumentation-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: pip install uv
    
    - name: Set up Python environment for data processing
      run: |
        cd data-processing
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
    
    - name: Install Python dependencies for update script
      run: |
        pip install requests pyyaml
    
    - name: Run update script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/update-instrumentation-list.py
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: 'chore: update instrumentation list with latest data'
        title: 'Update instrumentation list with latest data'
        body: |
          ## Automated Update
          
          This PR updates the instrumentation list with the latest data from the OpenTelemetry Java Instrumentation repository.
          
          ### Changes:
          - Downloaded latest instrumentation-list.yaml
          - Regenerated enriched JSON with semantic convention data
          
          ### Source:
          https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/instrumentation-list.yaml
          
          **Auto-generated by GitHub Actions**
        branch: update-instrumentation-list
        delete-branch: true