name: Update Instrumentation List

on:
  # Run daily at 9 AM UTC
  schedule:
    - cron: '0 9 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-instrumentation-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: pip install uv
    
    - name: Set up Python environment for data processing
      run: |
        cd data-processing
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
    
    - name: Install Python dependencies for update script
      run: |
        pip install requests pyyaml
    
    - name: Run update script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/update-instrumentation-list.py
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Check for changes
      id: git-check
      run: |
        echo "Checking for changes..."
        git status
        git diff --name-only
        
        # Check if there are any changes (avoid showing diff content which might contain sensitive data)
        if ! git diff --exit-code --quiet; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected in instrumentation files"
          echo "Modified files:"
          git diff --name-only
        else
          echo "No changes detected"
        fi
    
    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_TOKEN }}
        commit-message: 'chore: update instrumentation list with latest data'
        title: 'Update instrumentation list with latest data'
        body: |
          ## Automated Update
          
          This PR updates the instrumentation list with the latest data from the OpenTelemetry Java Instrumentation repository.
          
          ### Changes:
          - Downloaded latest instrumentation-list.yaml
          - Regenerated enriched JSON with semantic convention data
          
          ### Source:
          https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/instrumentation-list.yaml
          
          **Auto-generated by GitHub Actions**
        branch: update-instrumentation-list
        base: main
        delete-branch: true